### ISSUE TITLE
albums crud  routes

### ISSUE THREAD

**Issue by mzelmanovich** [mzelmanovich/durrok-fompay#59]

**Comment by summergun** [comment]
/albums (get, post); /albums/:id (get, put, delete), /albums/:id/genre (get, put, delete), /albums/:id/song (get, put, delete), /albums/:id/order(get, put, delete)

**Comment by summergun** [comment]
should be able to list all albums, list single albums. Add, edit delete album (admin user only), when adding the album, make the association with genre and song
