### ISSUE TITLE
crud orders

### ISSUE THREAD

**Issue by mzelmanovich** [mzelmanovich/durrok-fompay#78]

**Comment by mzelmanovich** [comment]
i think we need to update this to have belong to many albums, songs, payments....

**Comment by mzelmanovich** [comment]
@summergun what do you think?

**Comment by summergun** [comment]
@mzelmanovich, or we can add another model called cart, order.belongsto(cart), cart.belongsTo(User), Cart.belongsToMany(Albums); Albums.belongsToMany(Cart)
